### ISSUE TITLE
Clicking outside the GUI will cause a crash

### ISSUE THREAD

**Issue by theLittleStone** [Gu-ZT/gugle-carpet-addition#1]
After installing the mod in minecraft version 1.16, click the REI sidebar to view the recipe of the item, a crash has occurred
crash report: 
``` 
---- Minecraft Crash Report ----
// Oops.

Time: 2022/8/24 下午9:54
Description: Container click

java.lang.IndexOutOfBoundsException: Index -999 out of bounds for length 90
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.screen.ScreenHandler.handler$cga000$doClick(ScreenHandler:1251)
	at net.minecraft.screen.ScreenHandler.method_30010(ScreenHandler)
	at net.minecraft.screen.ScreenHandler.onSlotClick(ScreenHandler:177)
	at net.minecraft.client.network.ClientPlayerInteractionManager.clickSlot(ClientPlayerInteractionManager:398)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.onMouseClick(HandledScreen:562)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.mouseClicked(HandledScreen:358)
	at net.minecraft.client.Mouse.method_1611(Mouse:92)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:435)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:92)
	at net.minecraft.client.Mouse.method_22686(Mouse:162)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
	at net.minecraft.client.Mouse.method_22684(Mouse:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:109)
	at net.minecraft.client.util.Window.swapBuffers(Window:308)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1068)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.MinecraftClient.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:15906)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:702)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.MinecraftClient.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:15906)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:702)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.MinecraftClient.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:15906)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:702)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.MinecraftClient.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:15906)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:702)
	at net.minecraft.client.main.Main.main(Main:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.class_1703.handler$cga000$doClick(class_1703.java:1251)
	at net.minecraft.class_1703.method_30010(class_1703.java)

-- Click info --
Details:
	Menu Type: minecraft:generic_9x6
	Menu Class: net.minecraft.class_1707
	Slot Count: 90
	Slot: -999
	Button: 0
	Type: THROW
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:521)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:226)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:197)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:438)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:92)
	at net.minecraft.client.Mouse.method_22686(Mouse:162)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
	at net.minecraft.client.Mouse.method_22684(Mouse:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:109)
	at net.minecraft.client.util.Window.swapBuffers(Window:308)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1068)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.MinecraftClient.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:15906)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:702)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.MinecraftClient.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:15906)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:702)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.MinecraftClient.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:15906)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:702)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.MinecraftClient.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:15906)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:702)
	at net.minecraft.client.main.Main.main(Main:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_476
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:521)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:226)
	at net.minecraft.world.World.addDetailsToCrashReport(World:1014)
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld:449)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient:2239)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:699)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.MinecraftClient.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:15906)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:702)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.MinecraftClient.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:15906)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:702)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.MinecraftClient.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:15906)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:702)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.MinecraftClient.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:15906)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:702)
	at net.minecraft.client.main.Main.main(Main:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 2 total; [class_746['The_Little_Stone'/2370, l='ClientLevel', x=-486.49, y=67.00, z=589.82], class_745['Alex'/2818, l='ClientLevel', x=-488.79, y=67.00, z=590.29]]
	Chunk stats: Client Chunk Cache: 1024, 552
	Level dimension: minecraft:overworld
	Level spawn location: World: (96,72,192), Chunk: (at 0,4,0 in 6,12; contains blocks 96,0,192 to 111,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8589625 game time, 9938180 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.class_310.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:15906)
	at net.minecraft.class_310.method_1514(class_310.java:702)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.class_310.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:15906)
	at net.minecraft.class_310.method_1514(class_310.java:702)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.class_310.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:15906)
	at net.minecraft.class_310.method_1514(class_310.java:702)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.class_310.modify$dhh000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:15906)
	at net.minecraft.class_310.method_1514(class_310.java:702)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 18.0.1.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 815173856 bytes (777 MB) / 2013265920 bytes (1920 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Suspected Mods: None
	Fabric Mods: 
		antighost: AntiGhost 1.16.5-fabric0.30.0-1.1.3
		appleskin: AppleSkin 2.4.0+mc1.16.5
		authme: Auth Me 2.1.0
		autofish: Autofish 0.9.2
		baritone: Baritone 1.6.3
		bbor: BoundingBoxOutlineReloaded 2.4-1.16.3
		betterf3: BetterF3 1.1.3
		caffeineconfig: CaffeineConfig 1.0.0
		carpet: Carpet Mod 1.4.44
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.39.0
		chime: Chime 1.1.3
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 1.6.59
		cloth-config2: Cloth Config v4 4.12.41
		conditional-mixin: conditional mixin 0.3.1
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crowdin-translate: CrowdinTranslate 1.2
		custom-crosshair-mod: Custom Crosshair Mod 1.3.1-fabric
		customskinloader: CustomSkinLoader 14.14-SNAPSHOT-345
		dark-loading-screen: Dark Loading Screen 1.6.3
		easiervillagertrading: EasierVillagerTrading 1.16.5-fabric0.30.0-1.5.4
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.14.9
		fastchest: FastChest 1.2+1.16
		fpsreducer: FPS Reducer 1.24-mc1.16.5
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		gca: GugleCarpetAddition 2.0.7
		ias: In-Game Account Switcher 7.2.0
		iknowwhatimdoing: I Know What I'm Doing 4.1.0
		indium: Indium 1.0.0+mc1.16.5
		inventoryhud: Inventory HUD + 3.4.1
		inventoryprofilesnext: Inventory Profiles Next 1.5.3
		iris: Iris 1.2.6
		itemscroller: Item Scroller 0.15.0-dev.20210917.191808
		java: Java HotSpot(TM) 64-Bit Server VM 18
		lazydfu: LazyDFU 0.1.2
		litematica: Litematica 0.0.0-dev.20210917.192300
		lithium: Lithium 0.6.6
		magiclib: MagicLib 0.5.37
		magiclib-1_16_5: MagicLib for 1.16.5 0.5.37
		malilib: MaLiLib 0.10.0-dev.21+arne.8
		masa_gadget_mod: Masa Gadget 3.0.0
		masa_gadget_mod-1_16_5: Masa Gadget for 1.16.5 3.0.0
		mcwifipnp: LAN World Plug-n-Play 1.5.6
		minecraft: Minecraft 1.16.5
		minihud: MiniHUD 0.19.0-dev.20210917.191825
		modmenu: Mod Menu 1.16.23
		multiconnect-api: MultiConnect API 1.3.36
		notenoughcrashes: Not Enough Crashes 4.1.4+1.16.5
		ommc: Oh My Minecraft Client 0.5
		ommc-1_16_5: Oh My Minecraft Client for 1.16.5 0.5
		openloader: OpenLoader 1.0.2
		orderly: Orderly 2.0.0-alpha.10-1.16
		org_anarres_jcpp: jcpp 1.4.14
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_yaml_snakeyaml: snakeyaml 1.30
		pca: Plusls carpet addition mod 0.2.5
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.16.5-build.56
		roughlyenoughitems: Roughly Enough Items 5.12.385
		roughlyenoughitems-api: REI (API) 5.12.385
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.385
		roughlyenoughitems-runtime: REI (Runtime) 5.12.385
		shulkerboxtooltip: Shulker Box Tooltip 2.3.8+1.16.5
		skyblock: SkyBlock 2.1.4
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.2.0+build.4
		sodium-extra: Sodium Extra 0.4.6+mc1.16.5-build.44
		starlight: Starlight 0.0.3
		syncmatica: Syncmatica 1.16.5-0.3.2
		timetolive: Time To Live 0.3
		tweakeroo: Tweakeroo 0.10.0-dev.20210917.191839
		worldedit: WorldEdit 7.2.5+57d5ac9
		worldeditcui: WorldEditCUI 1.16.5+02
		wthit: wthit 2.10.15
		xaerominimap: Xaero's Minimap 22.13.2
		xaeroworldmap: Xaero's World Map 1.26.6
	Loaded Shaderpack: (off)
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.01, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, bbor, Fabric Mods, file/下北泽土特产-v0.2.zip (incompatible), file/[1.16]Xaeros世界地图&amp;小地图汉化210826.zip, file/[汉化1.16.5]MASA全家桶汉化包zmdf&amp;Sinbing.zip (incompatible), file/透明盔甲与马猴烧酒.zip, file/Dramatic+Sky+for+1.16+.zip, file/R_Complementary.Pack1.16.2+.zip, file/XeKr 原版红显16_19plus2.4.zip (incompatible)
	Current Language: 简体中文 (中国)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	Client Crashes Since Restart: 5
	Integrated Server Crashes Since Restart: 0
```

**Comment by Gu-ZT** [comment]
Try whether the `2.1.0` version still has this problem

**Comment by theLittleStone** [comment]
Still cause crash

**Comment by Gu-ZT** [comment]
Try whether the `2.2.0` version

**Comment by theLittleStone** [comment]
I haven't found any problems so far, thank you
