### ISSUE TITLE
Mod导致服务器无法启动

### ISSUE THREAD

**Issue by Pau1am** [Gu-ZT/gugle-carpet-addition#3]
服务器游戏版本: 1.19.2
Fabric加载器版本: 0.14.9
gugle-carpet-addition版本: 2.2.0

安装最新版的Mod后，服务器无法正常启动，并显示以下报错:

> [12:13:36] [main/ERROR]: Mixin apply for mod gca failed gca.mixins.json:AbstractContainerMenuMixin from mod gca -> net.minecraft.class_1703: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_7761 was not located in the target class net.minecraft.class_1703. Using refmap gugle-carpet-addition-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_7761 was not located in the target class net.minecraft.class_1703. Using refmap gugle-carpet-addition-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:270) ~[server-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:20) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:16) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:32) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:66) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) [?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) [server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) [server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) [server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
[12:13:36] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:20) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:16) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:32) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:66) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 3 more

**Comment by Pau1am** [comment]
补充信息，服务器已安装的mod列表如下:
![image](https://user-images.githubusercontent.com/41251296/187057195-421d927a-2e82-4dfc-a54d-128b0954d1bd.png)

**Comment by Pau1am** [comment]
经过测试，删除最新版gugle carpet addition 2.2.0 mod,或者使用旧版的gugle carpet addition 2.1.0均可使服务器正常启动

**Comment by Gu-ZT** [comment]
You can in [this](https://github.com/Gu-ZT/gugle-carpet-addition/actions/runs/2942677248) download a new version
