### ISSUE TITLE
Mod导致服务器数据包无法处理的问题

### ISSUE THREAD

**Issue by Pau1am** [Gu-ZT/gugle-carpet-addition#4]
服务器游戏版本: 1.19.2
Fabric加载器版本: 0.14.9
gugle-carpet-addition版本: 2.1.0

安装mod后可正常启动服务器，当玩家在服务器里进行物品移动操作时（例如从箱子拿取物品，或将身上的物品分一半等等操作），操作将大概率发生回弹（例如从身上一组物品分出一半物品后，等待约一秒后分出的物品会回弹到一组物品的状态）。
检查后台，发现以下报错

> [12:24:18] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2813@4d8d4b66, suppressing error
net.minecraft.class_148: Container click
	at net.minecraft.class_1703.method_7593(class_1703.java:303) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12076(class_3244.java:1770) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_12191(class_2813.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_11054(class_2813.java:13) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbj000$modifiedRunLoop(MinecraftServer.java:2894) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index -999 out of bounds for length 63
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.class_2371.get(class_2371.java:47) ~[server-intermediary.jar:?]
	at net.minecraft.class_1703.handler$bpm000$doClick(class_1703.java:2387) ~[server-intermediary.jar:?]
	at net.minecraft.class_1703.method_30010(class_1703.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_1703.method_7593(class_1703.java:293) ~[server-intermediary.jar:?]
	... 18 more

服务器Mod列表如下:
![image](https://user-images.githubusercontent.com/41251296/187057499-a2f3e302-8692-4882-a109-7bc8c677e0b4.png)

经过测试，删除gugle carpet addition 2.1.0后重启服务器则不存在此问题

**Comment by Gu-ZT** [comment]
See #1  for this problem
