### ISSUE TITLE
[Bug] 现版本目前不支持1.20.4，希望重新提升版本到1.20.4

### ISSUE THREAD

**Issue by liangmiQwQ** [Gu-ZT/gugle-carpet-addition#54]
### OS Version - 操作系统

MacOS

### Minecraft Version Details - Minecraft 版本信息

1.20.4 / 1.20.1

### Version Details - 版本信息

2.8.0+build.43

### Existing behavior - 现有行为

使用1.20.4版本的minecraft运行此mod后报错
```Command: /Library/Java/JavaVirtualMachines/microsoft-17.jdk/Contents/Home/bin/java -Xmx4096m "-Dfile.encoding=UTF-8" "-Dsun.stdout.encoding=UTF-8" "-Dsun.stderr.encoding=UTF-8" "-Djava.rmi.server.useCodebaseOnly=true" "-Dcom.sun.jndi.rmi.object.trustURLCodebase=false" "-Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false" "-Dlog4j2.formatMsgNoLookups=true" "-Dlog4j.configurationFile=/Users/liangmi/Desktop/好东西/modTest/minecraft/versions/1.20.4/log4j2.xml" "-Dminecraft.client.jar=/Users/liangmi/Desktop/好东西/modTest/minecraft/versions/1.20.4/1.20.4.jar" "-Xdock:name=Minecraft 1.20.4" "-Xdock:icon=/Users/liangmi/Desktop/好东西/modTest/minecraft/assets/objects/f0/f00657542252858a721e715a2e888a9226404e35" "-Duser.home=/Users/liangmi/Desktop/好东西/modTest" -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC "-XX:G1NewSizePercent=20" "-XX:G1ReservePercent=20" "-XX:MaxGCPauseMillis=50" "-XX:G1HeapRegionSize=32m" -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods "-Dfml.ignoreInvalidMinecraftCertificates=true" "-Dfml.ignorePatchDiscrepancies=true" -XstartOnFirstThread "-Djava.library.path=/Users/liangmi/Desktop/好东西/modTest/minecraft/versions/1.20.4/natives-osx-x86_64" "-Djna.tmpdir=/Users/liangmi/Desktop/好东西/modTest/minecraft/versions/1.20.4/natives-osx-x86_64" "-Dorg.lwjgl.system.SharedLibraryExtractPath=/Users/liangmi/Desktop/好东西/modTest/minecraft/versions/1.20.4/natives-osx-x86_64" "-Dio.netty.native.workdir=/Users/liangmi/Desktop/好东西/modTest/minecraft/versions/1.20.4/natives-osx-x86_64" "-Dminecraft.launcher.brand=HMCL" "-Dminecraft.launcher.version=3.5.7" -cp /Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/net/fabricmc/intermediary/1.20.4/intermediary-1.20.4.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/net/fabricmc/fabric-loader/0.15.7/fabric-loader-0.15.7.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/com/mojang/authlib/6.0.52/authlib-6.0.52.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-macos.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-macos-arm64.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-macos.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-macos-arm64.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-macos.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-macos-arm64.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-macos.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-macos-arm64.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-macos.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-macos-arm64.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-macos.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-macos-arm64.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-macos.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-macos-arm64.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar:/Users/liangmi/Desktop/好东西/modTest/minecraft/versions/1.20.4/1.20.4.jar net.fabricmc.loader.impl.launch.knot.KnotClient --username liangmimi --version 1.20.4 --gameDir /Users/liangmi/Desktop/好东西/modTest/minecraft --assetsDir /Users/liangmi/Desktop/好东西/modTest/minecraft/assets --assetIndex 12 --uuid 6565663da099442d8639b84412238274 --accessToken <access token> --clientId "\${clientid}" --xuid "\${auth_xuid}" --userType msa --versionType "HMCL 3.5.7" --width 854 --height 480
[14:37:33] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[14:37:33] [ForkJoinPool-1-worker-2/WARN]: Mod gca uses the version mc1.20.1-2.8.0+build.43 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'mc1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:37:33] [main/INFO]: Loading 57 mods:
	- carpet 1.4.128+v231205
	- fabric-api 0.96.11+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
       (省略FabricAPi下mods)
   	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- gca mc1.20.1-2.8.0+build.43
	(仅加载了fabric-api, carpet, gca)
	- java 17
	- minecraft 1.20.4
[14:37:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/liangmi/Desktop/%e5%a5%bd%e4%b8%9c%e8%a5%bf/modTest/minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:37:34] [main/INFO]: Compatibility level set to JAVA_17
[14:37:35] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[14:37:42] [main/WARN]: Failed to get system info for GL Caps
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:185) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:174) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:874) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2609) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2580) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-06-02 14:37:42
Description: Bootstrap

java.lang.ExceptionInInitializerError
	at net.minecraft.class_2358.method_10199(class_2358.java:336)
	at net.minecraft.class_2966.method_12851(class_2966.java:54)
	at net.minecraft.client.main.Main.main(Main.java:170)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1743 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_6089.method_9530(class_6089.java:65)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1118)
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1114)
	at net.minecraft.class_4970.method_9549(class_4970.java:405)
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1391)
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:929)
	at net.minecraft.class_2246.<clinit>(class_2246.java:1253)
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method stripped(Lnet/minecraft/class_1838;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in gca.mixins.json:AxeItemMixin from mod gca failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap gugle-carpet-addition-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraft.class_2358.method_10199(class_2358.java:336)
	at net.minecraft.class_2966.method_12851(class_2966.java:54)

-- Initialization --
Details:
	Modules:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:170)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Mac OS X (x86_64) version 14.5
	Java Version: 17.0.4.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
	Memory: 317064192 bytes (302 MiB) / 570425344 bytes (544 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M2
	Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Avalanche + Blizzard
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M2
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 17408.00
	Virtual memory used (MB): 12802.70
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 416.44
	JVM Flags: 10 total; -Xmx4096m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods
	Fabric Mods:
		carpet: Carpet Mod 1.4.128+v231205
		fabric-api: Fabric API 0.96.11+1.20.4
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.15+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.4+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.4+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.1+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.26+58f8c0124f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.9+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.65+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.14+080016e44f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.19+58f8c0124f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.53+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.1+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.56+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.0+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.20+df798a894f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.11+eb30349a4f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		gca: GugleCarpetAddition mc1.20.1-2.8.0+build.43
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.4
	Launched Version: 1.20.4
	Launcher name: HMCL
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: ERR
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: zh_CN_#Hans
	CPU: <unknown>
``` 

### Expected behavior - 预期行为

正常启动游戏

### To Reproduce - 复现问题

使用1.20.4的Minecraft版本而不是1.20.1

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by liu-zhou-L** [comment]
你怎么下载的GugleCarpetAddition mc1.20.1-2.8.0，[gugle-carpet-addition-2.7.0-1.20.4.jar](https://github.com/Gu-ZT/gugle-carpet-addition/releases/download/2.7.0/gugle-carpet-addition-2.7.0-1.20.4.jar)是可以用的
