### ISSUE TITLE
假人無法駐留

### ISSUE THREAD

**Issue by zhao-ng327** [Gu-ZT/gugle-carpet-addition#65]
### OS Version - 操作系统

Windows

### Minecraft Version Details - Minecraft 版本信息

1.20.4 fabric server

### Version Details - 版本信息

2.7.0

### Existing behavior - 现有行为

假人駐留開啟後，若假人多於一個會導致伺服器崩潰
log如下

Description: Ticking player

java.lang.NullPointerException: Cannot invoke "dev.dubhe.gugle.carpet.tools.FakePlayerInventoryContainer.tick()" because the return value of "java.util.HashMap.get(Object)" is null
	at net.minecraft.class_1657.handler$zij000$gca$tick(class_1657.java:5835)
	at net.minecraft.class_1657.method_5773(class_1657.java:333)
	at net.minecraft.class_3222.method_14226(class_3222.java:519)
	at carpet.patches.EntityPlayerMPFake.method_5773(EntityPlayerMPFake.java:167)
	at net.minecraft.class_3218.method_18762(class_3218.java:761)
	at net.minecraft.class_1937.method_18472(class_1937.java:492)
	at net.minecraft.class_3218.method_31420(class_3218.java:399)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:363)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:842)

### Expected behavior - 预期行为

正常使用

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by Seungmin922** [comment]
我现在这个问题有点不一样.就是无法生成那个文件,不知道是模组冲突还是bug @zhao-ng327

**Comment by Seungmin922** [comment]
[latest.log](https://github.com/user-attachments/files/17002447/latest.log)
