### ISSUE TITLE
安装MOD后服务器无法启动

### ISSUE THREAD

**Issue by WhitePaper233** [Gu-ZT/gugle-carpet-addition#7]
服务端版本: Minecraft 1.18.2 with Fabric Loader 0.14.8

安装的模组:
```
- appleskin 2.4.1+mc1.18.2
- bbor 2.5-1.18.2
- carpet 1.4.69
- carpet-extra 1.4.72
- carpet-tctc-addition 1.1.8+94239b2
- carpet-tis-addition 1.33.0
- cloth-basic-math 0.6.0 via cloth-config
- cloth-config 6.2.57
- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
- conditional-mixin 0.2.0 via carpet-tis-addition
- fabric 0.51.1+1.18.2
- fabric-api-base 0.4.4+d7c144a860 via fabric
- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
- fabric-containers-v0 0.1.21+d7c144a860 via fabric
- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
- fabric-dimensions-v1 2.1.17+2540745460 via fabric
- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
- fabric-item-api-v1 1.4.0+4457765560 via fabric
- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
- fabric-resource-loader-v0 0.5.2+446e059560 via bbor
- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
- fabricloader 0.14.8
- gca 2.4.0-1.14
- java 18
- krypton 0.1.9
- lithium 0.7.9
- minecraft 1.18.2
- org_yaml_snakeyaml 1.30 via carpet-tis-addition
- pca 0.2.5-beta+8e41bb1
- servux 0.1.0
- xaerominimap 22.15.1
- xaeroworldmap 1.28.0
```

报错信息：
```
[21:20:20] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[21:20:22] [main/ERROR]: Mixin apply for mod gca failed gca.mixins.json:AbstractContainerMenuMixin from mod gca -> net.minecraft.class_1703: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on doClick could not find any targets matching 'Lnet/minecraft/class_1703;method_7593(IILnet/minecraft/class_1713;Lnet/minecraft/class_1657;)Lnet/minecraft/class_1799;' in net.minecraft.class_1703. Using refmap gugle-carpet-addition-refmap.json [PREINJECT Applicator Phase -> gca.mixins.json:AbstractContainerMenuMixin from mod gca -> Prepare Injections ->  -> handler$bpj000$doClick(IILnet/minecraft/class_1713;Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on doClick could not find any targets matching 'Lnet/minecraft/class_1703;method_7593(IILnet/minecraft/class_1713;Lnet/minecraft/class_1657;)Lnet/minecraft/class_1799;' in net.minecraft.class_1703. Using refmap gugle-carpet-addition-refmap.json [PREINJECT Applicator Phase -> gca.mixins.json:AbstractContainerMenuMixin from mod gca -> Prepare Injections ->  -> handler$bpj000$doClick(IILnet/minecraft/class_1713;Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:261) ~[server-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) [?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) [server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) [server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) [server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
[21:20:22] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1703 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:261) ~[server-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:261) ~[server-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [gca.mixins.json:AbstractContainerMenuMixin from mod gca] from phase [DEFAULT] in config [gca.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:261) ~[server-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on doClick could not find any targets matching 'Lnet/minecraft/class_1703;method_7593(IILnet/minecraft/class_1713;Lnet/minecraft/class_1657;)Lnet/minecraft/class_1799;' in net.minecraft.class_1703. Using refmap gugle-carpet-addition-refmap.json [PREINJECT Applicator Phase -> gca.mixins.json:AbstractContainerMenuMixin from mod gca -> Prepare Injections ->  -> handler$bpj000$doClick(IILnet/minecraft/class_1713;Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:261) ~[server-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 3 more
```

**Comment by Gu-ZT** [comment]
目测应该是和 krypton 不兼容

**Comment by Glucy-2** [comment]
经过我的测试并不是和 krypton 不兼容
能够启动的最高的gca版本为2.0.5，2.0.7及以后的版本都不行
我的服务端版本为1.19.2

**Comment by Glucy-2** [comment]
找到原因了，gca只在curseforge发布了所有mod版本，还将modrinth平台上适用于1.14-1.15的版本错误地标注为适用1.14-1.19版本，到curseforge下载适用的版本就好了
